### PR TITLE
Fixes prover behavior with singleton proof trees

### LINKED ISSUE #852: Prover fails to build valid proofs when `ecK` coincides with the number of blocks in the file.
The prover will currently not generate valid proofs when `ecK` is equal to the number of blocks in the file. The following test case (to be patched onto [`testprover.nim`](https://github.com/codex-storage/nim-codex/blob/master/tests/codex/slots/testprover.nim)) illustrates the issue:

```nim
  test "Should generate valid proofs when k = ecK":
    let
      (_, _, verifiable) =
        await createVerifiableManifest(
          store,
          2,
          2, 1,
          DefaultBlockSize,
          DefaultCellSize)

    let
      r1cs = "tests/circuits/fixtures/proof_main.r1cs"
      wasm = "tests/circuits/fixtures/proof_main.wasm"
      circomBackend = CircomCompat.init(r1cs, wasm)
      prover = Prover.new(store, circomBackend, 5)
      challenge = 1234567.toF.toBytes.toArray32
      (inputs, proof) = (await prover.prove(1, verifiable, challenge)).tryGet

    check:
      (await prover.verify(proof, inputs)).tryGet == true
```

### PR DESCRIPTION
**Pull request by gmega**
fixes #852 

This PR adds a test and updated circuit assets which fix the bug in #852. The issue was that the convention for handling single-block trees was not entirely correct at the circuit, [which has now been fixed](https://github.com/codex-storage/codex-storage-proofs-circuits/commit/6e9fcc632c9599679bca8788c9c4221eabdb5e21).

The PR also contains updates that should make it easier to generate valid JSON Circom inputs from Codex tests, which should make the process of writing tests to debug circuits simpler.

### CODE REVIEW

**Review by tbekas — APPROVED** [review]
LGTM

File: codex/slots/proofs/backends/circomcompat.nim [hunk 1]
```diff
@@ -51,25 +83,18 @@ proc release*(self: CircomCompat) =
 
 proc prove*[H](
```
Comment (dryajov) [inline codex/slots/proofs/backends/circomcompat.nim:84]: should this be public?

Comment (gmega) [reply codex/slots/proofs/backends/circomcompat.nim:84]: Guess it doesn't have to. Will make it private.

File: codex/slots/sampler/utils.nim [hunk 2]
```diff
@@ -80,7 +69,7 @@ func cellIndices*(
   numCells: Natural, nSamples: Natural): seq[Natural] =
 
   var indices: seq[Natural]
-  while (indices.len < nSamples):
-    let idx = cellIndex(entropy, slotRoot, numCells, indices.len + 1)
-    indices.add(idx.Natural)
+  for i in 1..nSamples:
+    indices.add(cellIndex(entropy, slotRoot, numCells, i))
```
Comment (dryajov) [inline codex/slots/sampler/utils.nim:73]: This changes the logic by passing a different `counter` to `cellIndex`, this looks like a breaking change?

File: tests/codex/slots/testprover.nim [hunk 3]
```diff
@@ -24,52 +24,69 @@ import ./backends/helpers
...
           store,
-          numDatasetBlocks,
-          ecK, ecM,
+          8, # number of blocks in the original dataset (before EC)
+          5, # ecK
+          3, # ecM
           blockSize,
           cellSize)
 
-  teardown:
```
Comment (dryajov) [inline tests/codex/slots/testprover.nim:60]: Why remove this?

Comment (gmega) [reply tests/codex/slots/testprover.nim:60]: This is just a weird diff, the teardown is still there.

File: codex/slots/proofs/backends/circomcompat.nim (hunk 1 above)
Comment (gmega) [reply codex/slots/proofs/backends/circomcompat.nim]: Fixed!

File: codex/slots/sampler/utils.nim (hunk 2 above)
Comment (dryajov) [reply codex/slots/sampler/utils.nim:73]: Ah, you're right. The previous logic is quite confusing indeed.

**Review by dryajov — APPROVED** [review]
LGTM

File: codex/slots/sampler/utils.nim [hunk 4]
```diff
@@ -47,10 +38,8 @@ func floorLog2*(x : int) : int =
   return k
 
 func ceilingLog2*(x : int) : int =
-  if (x == 0):
-    return -1
-  else:
-    return (floorLog2(x-1) + 1)
+  doAssert ( x > 0 )
```
Comment (emizzle) [inline codex/slots/sampler/utils.nim:41]: Might be a good idea to provide a reason string here so if we do encounter this defect, we can see something that’ll give us a clue as to what went wrong. Otherwise, we might not even get a stack trace to help.

Comment (emizzle) [reply codex/slots/sampler/utils.nim:41]: Same with line 32

**Comment by 2-towns** [comment]
Do we still need https://github.com/codex-storage/nim-codex/blob/1f49f86131fbc9721fa1d136705a1aec4601572e/codex/node.nim#L432-L436 @gmega ?

**Comment by gmega** [comment]
@2-towns yes :flushed:

**Comment by 2-towns** [comment]
And for this one (indirectly related), it was specific for the workshop: 

https://github.com/codex-storage/nim-codex/blob/1f49f86131fbc9721fa1d136705a1aec4601572e/codex/node.nim#L266-L270

@gmega
