### PR TITLE
fix: load slots on sales module start

### LINKED ISSUE #294: Add node restart

### LINKED ISSUE #505: Load Slots on Node Start
Recover the state from blockchain upon node start

### PR DESCRIPTION
**Pull request by AuHau**
Closes #294  
Closes #505

### CODE REVIEW

File: tests/codex/sales/testsales.nim [hunk 1]
```diff
@@ -22,6 +22,104 @@ import ../helpers/eventually
...
+    # randomly selected for the agent, and we also won't know the value of
+    # `failed`/`fulfilled`/`cancelled` futures, so we need to compare
+    # the properties we know
+    # TODO: when calling sales.load(), slot index should be restored and not
+    # randomly re-assigned, so this may no longer be needed
+    proc `==` (data0, data1: SalesData): bool =
+      return data0.requestId == data1.requestId and
+             data0.request == data1.request
+
+    check eventuallyCheck sales.agents.len == 2
```
Comment (emizzle) [inline tests/codex/sales/testsales.nim:120]: I think we can use `eventually` (instead of `eventuallyCheck`) from `asynctest`, no?

File: tests/codex/sales/testsales.nim [hunk 2]
```diff
@@ -22,6 +22,104 @@ import ../helpers/eventually
...
+    let expected = SalesData(requestId: request.id, request: some request)
+    # because sales.load() calls agent.start, we won't know the slotIndex
+    # randomly selected for the agent, and we also won't know the value of
+    # `failed`/`fulfilled`/`cancelled` futures, so we need to compare
+    # the properties we know
+    # TODO: when calling sales.load(), slot index should be restored and not
+    # randomly re-assigned, so this may no longer be needed
+    proc `==` (data0, data1: SalesData): bool =
+      return data0.requestId == data1.requestId and
+             data0.request == data1.request
```
Comment (emizzle) [inline tests/codex/sales/testsales.nim:118]: Slot index and the state should now be restored, so we don't need this comment nor do I believe we need the `==`, as slot index should be compared.

**Review by emizzle — APPROVED** [review]
Nice work Adam! I'll approve now, but I think we should probably remove the `==`.

File: tests/codex/sales/testsales.nim (hunk 1 above)
Comment (AuHau) [reply tests/codex/sales/testsales.nim:120]: I saw your message in Discord, make sense 👍

File: tests/codex/sales/testsales.nim (hunk 2 above)
Comment (AuHau) [reply tests/codex/sales/testsales.nim:118]: Okey, I was not really analyzing this part, simply duplicated the test setup from bellow. I will modify it there as well then.

File: tests/codex/sales/testsales.nim (hunk 1 above)
Comment (AuHau) [reply tests/codex/sales/testsales.nim]: Hmm, it seems there are some differences between `eventuallyCheck` and `eventually`. 😳 The tests in this file that still use `eventuallyCheck` started to fail when moved to `eventually`. 😳

I will merge it in its current form, and once we decide to make the full switch in the codebase, we should take a look at this.

File: tests/codex/sales/testsales.nim (hunk 2 above)
Comment (emizzle) [reply tests/codex/sales/testsales.nim]: Thank you 🙏
